# Generated by Django 3.1.7 on 2021-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('primaryType', models.IntegerField(choices=[(1, 'BUG'), (2, 'DARK'), (3, 'DRAGON'), (4, 'GROUND'), (5, 'ELECTRIC'), (6, 'FAIRY'), (7, 'FIGHTING'), (8, 'FIRE'), (9, 'FLYING'), (10, 'GHOST'), (11, 'GRASS'), (12, 'ICE'), (13, 'NORMAL'), (14, 'POISON'), (15, 'PSYCHIC'), (16, 'ROCK'), (17, 'STEEL'), (18, 'WATER')])),
                ('secondaryType', models.IntegerField(choices=[(1, 'BUG'), (2, 'DARK'), (3, 'DRAGON'), (4, 'GROUND'), (5, 'ELECTRIC'), (6, 'FAIRY'), (7, 'FIGHTING'), (8, 'FIRE'), (9, 'FLYING'), (10, 'GHOST'), (11, 'GRASS'), (12, 'ICE'), (13, 'NORMAL'), (14, 'POISON'), (15, 'PSYCHIC'), (16, 'ROCK'), (17, 'STEEL'), (18, 'WATER')], null=True)),
            ],
        ),
    ]
