# Generated by Django 3.1.7 on 2021-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='secondaryType',
            field=models.IntegerField(blank=True, choices=[(1, 'BUG'), (2, 'DARK'), (3, 'DRAGON'), (4, 'GROUND'), (5, 'ELECTRIC'), (6, 'FAIRY'), (7, 'FIGHTING'), (8, 'FIRE'), (9, 'FLYING'), (10, 'GHOST'), (11, 'GRASS'), (12, 'ICE'), (13, 'NORMAL'), (14, 'POISON'), (15, 'PSYCHIC'), (16, 'ROCK'), (17, 'STEEL'), (18, 'WATER')], null=True),
        ),
    ]
